imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PubBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    neptune_coordinates_latitude: 54.3488976
    neptune_coordinates_longitude: 18.653141
    google_api_url: "https://maps.googleapis.com/maps/api/place"
    google_api_key: "AIzaSyDNOJqKuHJ6M-SqDLQfG_-uNXAwmEanqBg"
    google_api_lang: "pl"
    bar_search_radius: 2000
    bar_search_location_type: bar

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

fos_rest:
    view:
        formats:
            xml: true
            json: true
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException': 406
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true
        enabled: true
        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            - { path: '^/pubApi/' ,methods: ['GET'], priorities: ['json', 'xml'], fallback_format: false, prefer_extension: true }
