services:
    neptune.latitude:
        class: PubBundle\Domain\ValueObject\Latitude
        arguments: [%neptune_coordinates_latitude%]
    neptune.longitude:
        class: PubBundle\Domain\ValueObject\Longitude
        arguments: [%neptune_coordinates_longitude%]
    neptune.location:
        class: PubBundle\Domain\ValueObject\Location
        arguments: ["@neptune.latitude", "@neptune.longitude"]
    location.factory.fromCoordinates:
        class: PubBundle\Domain\Factory\CoordinatesCommaSeparatedLocationFactory
    location.kilometerDistanceCalculator:
        class: PubBundle\Component\Location\SimpleKilometerDistanceCalculator
    location.locationToPlaceIds.testReadRepository:
        class: PubBundle\Component\Location\TestLocationToPlaceIdsReadRepository
    place.locationRelationFactory:
        class: PubBundle\Domain\Factory\CalculatorBasedLocationRelationFactory
        arguments: ["@location.kilometerDistanceCalculator"]
    place.testReadRepository:
        class: PubBundle\Domain\ReadRepository\TestPlaceReadRepository
    place.testNearbyPlacesReadRepository:
        class: PubBundle\Domain\ReadRepository\TestNearbyPlacesReadRepository
        arguments: ["@place.testReadRepository", "@location.locationToPlaceIds.testReadRepository", "@place.locationRelationFactory"]
    # Google based searching
    barSearch.searchParameters.radius:
        class: PubBundle\Component\GooglePlaceSearcher\SearchParameter\RadiusSearchParameter
        arguments: [%bar_search_radius%]
    barSearch.searchParameters.locationtype:
        class: PubBundle\Component\GooglePlaceSearcher\SearchParameter\LocationTypeSearchParameter
        arguments: [%bar_search_location_type%]
    barSearch.nearbySearchParametersProvider:
        class: PubBundle\Component\BarSearch\BarNearbySearchParametersProvider
        arguments: ["@barSearch.searchParameters.radius", "@barSearch.searchParameters.locationtype"]
    googleSearcher.apiClient:
        class: PubBundle\Component\GooglePlaceSearcher\ZendHttpBasedPlaceApiClient
        arguments: [%google_api_url%, %google_api_key%, %google_api_lang%, "@logger"]
    googleSearcher.nearbayPlacesSearcher:
        class: PubBundle\Component\GooglePlaceSearcher\NearbyPlacesSearcher
        arguments: ["@googleSearcher.apiClient"]
    googleSearcher.resultMapper:
            class: PubBundle\Domain\ReadRepository\SimpleGoogleResultToPlaceMapper
    place.nearbyPlacesReadRepository:
        class: PubBundle\Domain\ReadRepository\GoogleNearbyPlacesReadRepository
        arguments: ["@googleSearcher.nearbayPlacesSearcher", "@barSearch.nearbySearchParametersProvider", "@googleSearcher.resultMapper", "@place.locationRelationFactory"]
